FROM maven:3.9-eclipse-temurin-21

WORKDIR /workspace

COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

EXPOSE 8080

CMD ["sh", "-lc", "mvn -DskipTests compile spring-boot:run -Dspring-boot.run.profiles=docker"]
